### ISSUE TITLE
If the path is not specified in json, then default should create folders based on thread numbers as well

### ISSUE THREAD

**Issue by ValentinJesse** [pboardman/4scanner#55]
This is the only thing that is missing from this script. This way everything would be more organized. I imagine that, with the current script, after a few weeks of saving from chan, my folder would be a mess with tens of thousands of photos in it

The default setting should create folders similar to this:

![chrome_2017-07-16_03-13-58](https://user-images.githubusercontent.com/7979136/28243706-2575397c-69d5-11e7-8f7d-6b5e7b901ed6.png)

Thanks!

**Comment by pboardman** [comment]
Interesting idea, but I think that `folder_name` should still be required and creating something like this:
![](http://i.imgur.com/zStjvI5.png)

Do you think it would be a good compromise? `folder_name` is important to have imo because you can search a lot of different things from a board and it would be hard to know what threads contained what based only on a thread number.

**Comment by ValentinJesse** [comment]
Sorry for not making myself clear. I agree, you should definitely keep the "folder_name". The only thing that i want is for the script to create additional folders (named after the threads) inside that "folder_name", just like in your image above.  

This way everything is more organized, and on top of it, if you ever lose your data, you can always use the thread titles to recover it from other websites that archive the content.

**Comment by pboardman** [comment]
Perfect then!
Would you like to impement this feature? Or else I can do it when I get some free time.

**Comment by ValentinJesse** [comment]
Hi! Since it's your code, i guess that you would be more efficient than me. I will wait for your implementation. Thank you!

**Comment by pboardman** [comment]
Fixed by #56
